name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: docker build go-neo4j
        run: |
          docker build ./backend --tag canerdikkollu/go-neo4j:$(date +%s)
          
      - name: docker build go-route-creator
        run: |
          docker build ./backend --tag canerdikkollu/go-route-creator:$(date +%s)
          
      - name: docker build go-anomaly-detection
        run: |
          docker build ./backend --tag canerdikkollu/go-anomaly-detection:$(date +%s)

      - name: docker push
        run: |
          docker push canerdikkollu/go-neo4j
          docker push canerdikkollu/go-route-creator
          docker push canerdikkollu/go-anomaly-detection

