name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_USER }}
      
      - name: docker build go-neo4j
        run: |
          docker build ./backend -t ${{ secrets.DOCKER_USER }}/go-neo4j:1.0.0
          
      - name: docker build go-route-creator
        run: |
          docker build ./backend -t ${{ secrets.DOCKER_USER }}/go-route-creator:1.0.0
          
      - name: docker build go-anomaly-detection
        run: |
          docker build ./backend -t ${{ secrets.DOCKER_USER }}/go-anomaly-detection:1.0.0

      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/go-neo4j:1.0.0
          docker push ${{ secrets.DOCKER_USER }}/go-route-creator:1.0.0
          docker push ${{ secrets.DOCKER_USER }}/go-anomaly-detection:1.0.0
